#! /usr/bin/env bash

# Author:  Thomas DEBESSE <dev@illwieckz.net>
# License: ISC

set -u -e -o pipefail

_help() {
	cat <<-EOF
	USAGE: ${0} -s SIZE INFILE OUTFILE
	EOF
}

_error() {
	printf 'ERROR: %s\n\n' "${1}"
	_help
	exit 1
}

_main() {
	case "${1:-}" in
		'-h'|'--help')
			_help
			exit
		;;
	esac

	if [ "${1:-}" != '-s' ]
	then
		_error 'first argument must be -s'
	fi

	if [ -z "${2:-}" ]
	then
		_error 'second argument must be a number'
	else
		SIZE="${2}"
	fi

	if [ -z "x${3:-}" ]
	then
		_error 'third argument must be the input file'
	else
		INFILE="${3}"
	fi

	if [ -z "x${4:-}" ]
	then
		_error 'fourth argument must be the output file'
	else
		OUTFILE="${4}"
	fi

	crunch -quiet -file "${INFILE}" -fileformat 'tga' -out '/dev/stdout' | convert -thumbnail "${SIZE}x${SIZE}" -auto-orient tga:- "png:${OUTFILE}"
}

_main "${@}"

#EOF
